logging:
  config: classpath:log4j2-prod.xml

server:
  port: 8080

spring:

  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://eningqu-platform-hk-inner.mysql.rds.aliyuncs.com:3306/eningqu_platform?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: eningqu_platform
    password: 1234ASDF$#@!

    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 10
    minIdle: 10
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 100
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

  #Redis配置
  redis:
    # 数据库索引（默认为0）
    database: 0
    # 服务器地址
    host: eningqu-platform-hk-inner.redis.rds.aliyuncs.com
    # 服务器连接端口
    port: 6379
    # 服务器连接密码（默认为空）
    password: 1234ASDF$#@!
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000


