spring:

  profiles:
    active: @profileActive@

  http:
    multipart:
      enabled: true
      max-file-size: 200MB

server:
  context-path: /
  port: 9090
#  tomcat:
#    uri-encoding: utf-8
#    remote-ip-header: x-forwarded-for
#    protocol-header: x-forwarded-proto
#    port-header: X-Forwarded-Port
#    max-connections: 10000
#    # 最大线程数
#    max-threads: 1000
#    # 最小备用线程数
#    min-spare-threads: 200
#    # 请求队列
#    accept-count: 500
#    use-forward-headers: true
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 15
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 64
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
  error:
    path: /api/error

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.eningqu.domain.api
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    auto-set-db-type: true
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper调试神器
    refresh-mapper: true
    metaObjectHandler: com.eningqu.common.mybatisplus.ApiMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#短信
sms:
  accessKeyId: LTAIHiWBxZajyM4X
  accessKeySecret: e8h4YW6B3ca6PjY3qLDj2VPTMgsOaJ
  signature: 道域科技
  #模板编码
  tplCode: SMS_171113598

  tag:
    # 道域科技
    NQKJ:
      account: CN4676136
      password: xblENLCgvff55d
      url: http://smssh1.253.com/msg/variable/json
      # 验证码过期时间（分）
      timeout: 5
      tpl[0]: 【道域科技】亲爱的用户，您的短信验证码{$var}，该验证码{$var}分钟内有效，请勿泄漏于他人！若非本人操作请忽略。
    # 纵横九州
#    ZHJZ:
#      account: N5655237
#      password: Pky4GRYitz4209
#      url: http://smssh1.253.com/msg/variable/json
#      # 验证码过期时间（分）
#      timeout: 5
#      tpl[0]: 【纵横九州】亲爱的用户，您的短信验证码{$var}，该验证码{$var}分钟内有效，请勿泄漏于他人！若非本人操作请忽略。

# 微信支付
wx:
  # 商户号
  mch_id: 1516774851
  # 商户号秘钥
  mch_key: D10056129C51732AA8BCC8D349BCC2E4
  # 商户证书路径
  mch_cert_path: D:\Futruedao\base-res\cert\apiclient_cert.p12
  # 支付回调通知URL
  pay_notify_url: http://120.78.169.242:9090/api/wx/pay/notify
  # 退款回调通知URL
  refund_notify_url: http://120.78.169.242:9090/api/wx/refund/notify
  # app应用
  app:
    # AiPen移动应用appid
    app_id: wxcd8c9aa2163b6d9c
  # 网站应用
#  qr:
#    app_id: wxe264fb311833d372
#    app_secret: bf7126283e1e21da1bcbaea6b0828f76

# 支付宝支付
ali:
  # 商户账号
  seller_email: 2292617501@qq.com
  # 商户ID
  seller_id: 2088331106978615
  # 应用appID
  app_id: 2018110862080495
  # 签名类型
  sign_type: RSA2
  # app应用私钥
  app_private_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw/3z/lpX0AWpHISTDXwxG2Rnw90VOSgu4lNhvcEPU1dt9KQcoQDG4eVCw2LmcamMv9QU/iugfxOh5T5xT2dK16ZFUjxWNzrsrBA56vCJ/Ln5Wec9F/vrYJIq0UW+etIimN/XG2Yqvdm/rZPmd1n5eu3wdVXd7zlGmEr5MZcRIEfoEwU5IFj+Kk/7f510TBH6511F6iIbzgo3xpqc2Xg64dMOvPXElAMP7Q+DR3Tf5Q78APPt0evnkvyZe9i7DQVrqrST6s+rV1R/lD5VEdIvDn2N5wg5zLFa+UKDQPH4acqca5gIT4zGY6xofKY4yhkPlNkeyVD7oYh6bl0ddgeC5wIDAQAB
  # 支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmttBbHY4pOaB5/YDdnh64G5gABho2KPCp9ybATBwquY+GBsMltataHUCnnTraOid/KuqYOudgB34ijdoDXrFjMd3SR6tWZkUSPs0OxouUbsq/TTEQFaASYZCKbPm/TaPccSznG+8hCAUWXToStMjYUGo7e0V4wfEtKCZRVNUBZgxeLNq/mZ+Sxxn3nfpYt32ANe28+BFQ6FW8ZWlP6O1EUZL01qItvx4TFd7jnMBwDC4pieYK2pLItpmNqZhdtCdDEmQjMJ49Ah2FRuhJS7RJxvfEX2r6gGWTNrNfYc/Vpu7ZrA8FitUAiI0PQMn3RQxFT5TefFl8J7ZAJCqppP6dQIDAQAB

  #知URL
  notify_url: http://api.futruedao.com/api/ali/pay/notify

#快递
exp:
  appId: 1362962
  appKey: 01ec23ee-8278-4a6e-b268-ba13d0251333

# 秘钥配置
keys:
  #RSA key
  rsa:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDcvVLbKflXgHLqYekwOmeCvEm2uXbRtMbAtNNWp5XqYTnn4mah0F0+qlUHQ0bdzN0rAnKfBBQugtugz9F5827fnn8mHsmXe3oW8v/o/tUaUlsJuCgT27c/Md0ulKZWQT6w7PpsROIo7IGdvaWh33acWY2NdTdGuu/UFOGtqrsCIQIDAQAB
    private-key: MIICWwIBAAKBgQDcvVLbKflXgHLqYekwOmeCvEm2uXbRtMbAtNNWp5XqYTnn4mah0F0+qlUHQ0bdzN0rAnKfBBQugtugz9F5827fnn8mHsmXe3oW8v/o/tUaUlsJuCgT27c/Md0ulKZWQT6w7PpsROIo7IGdvaWh33acWY2NdTdGuu/UFOGtqrsCIQIDAQABAoGAKCwQYzBtX15SC5PME2ndoq5PoAB6vklvDm0aNSAEqYYOOsQ6N2KrRZdMKCk3QXBiI8yrPYNJhPltrQOFNPN3jsZJYDiIb+6DAkc0O8UMka8xYebq2E1Blel67/dE0PbFyM+y+O/Cs2/GSgAgV2wPTrd8H5GOuLMxjCDAAlgpi9ECQQDxhqCfkmkXM0mJBRkZH/CLqFNRVcbDfRiCf649C0SnKqQ1lWnN57ZJk4kx7YhoZ49aPI3vLPN4J3rwOh0xu5qNAkEA6ffNYarGnWSvRiq91w/gGH7gCQIYuHUm2vYvnK5nGfc2C6UhUGpbOwd0lnyW+jWE1bOJrBFyGzgllJt6Z3FK5QJAcfcgm6suQ3BD5o+tRBm6G2wVxG9BFsVUZ19wDAXhIzAPw+j4v9vyO82OEy0ODJWxItcn8g+34p5eeDQzyl/HkQJAXB0NpSghLhJX1144g5ViewJoneNPbD/jXk2SjTM0sEpd4tPOe+SDqofS5PSEVFoBxEj9KNttez3tvcZAuL0n6QJAUDjSIzcP6OzDifEjvQEN3/NMprMXOm1zf5DxufDmtuUAQFLAhdjGcrmhRnFOvpWiGaKuh3qBZZ0H1xAR2Y+Bkw==
    # 七牛云配置
qiniu:
  domain: http://download.futruedao.com
  bucket: products-image
  access-key: fP6KfIAAIJG0ZpEQQGxwbfu6TZyF_r2mCt5GHRUb
  secret-key: V4cKW3F5X0BxyGFua_A606uuQB2asJUHIJTt03TX

